### ISSUE TITLE
Prices are a out by factor of 10x 

### ISSUE THREAD

**Issue by MilanAra88** [martinarva/dynamic_energy_cost#18]
Hi there,

The pricing that is calculated incorrectly by a factor of 10. 

For instance, when the elec rate is £0.17/kwh and the appliance has used 0.315 kwh - it should £0.059 but it is showing at £0.59
.
See images. Any idea? 

Many thanks, 

Milan 

<img width="195" alt="image" src="https://github.com/martinarva/dynamic_energy_cost/assets/43094647/3a27da28-470f-4cb7-a4d9-860288a5294a">

**Comment by martinarva** [comment]
Please provide states of the sensors you used in the integration input.

**Comment by MilanAra88** [comment]
Thanks Martin,

This is the rate sensor: 
<img width="1103" alt="image" src="https://github.com/martinarva/dynamic_energy_cost/assets/43094647/55d333db-4847-4439-9229-23486da277d4">

Device Sensor: 
![image](https://github.com/martinarva/dynamic_energy_cost/assets/43094647/eec8dcc2-b158-43c9-9b42-4a4f301cafe9)

**Comment by martinarva** [comment]
I don't know why it's off. Could you please send the picture of the power entity graph?

Does your device have also energy sensor (kWh) and could you test it with the energy sensor?

Calculation with energy sensor is more precise than using the integration left method with power sensor. However difference should me marginal on 10x

**Comment by MilanAra88** [comment]
hi Marin, 

This is strange - the real time costs seem to be calculating correctly by the daily, monthly, and year figures are way out. 

Have you seen any other users with similar feedback?

**Comment by martinarva** [comment]
> hi Marin,
> 
> This is strange - the real time costs seem to be calculating correctly by the daily, monthly, and year figures are way out.
> 
> Have you seen any other users with similar feedback?

No, i haven't. I have a few power based test sensors running and they are correct.

**Comment by martinarva** [comment]
@MilanAra88 , i did some testing and compared it to the HA reiman sum + utility meter method and looks like its working properly.

I feed in my sensor.ss_load_power:
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: SS Load power

and sensor.nordpool_import (price sensor)
unit_of_measurement: EUR/kWh
friendly_name: nordpool_import


About an hour and cost is 0.35€. Real time cost fluctuates, but average is about 0.35€/h, so it shpould be correct. It's not 10x off at least.
![Screenshot 2024-05-13 at 11 43 35](https://github.com/martinarva/dynamic_energy_cost/assets/77044330/bef4bbab-c50a-4ecc-9b08-93cfb05e9e52)

**Comment by andiukas** [comment]
Same problem, consumption of the kettle after switching on twice
![image](https://github.com/martinarva/dynamic_energy_cost/assets/44068098/ca7c364d-3067-4f64-b5ba-154a01a3ac93)

**Comment by MilanAra88** [comment]
The workaround i have used seems to work great! : https://community.home-assistant.io/t/solved-calculate-cost-for-individual-device-cost-kwh/523880/8?u=baljci333

I still use this nice work from Martin for the real time costs as this seems to be right!

**Comment by martinarva** [comment]
I'm still puzzled why this 10x error occurs. 

Btw, @MilanAra88 , @andiukas  do you have energy (kwh) sensor for your device?

**Comment by MilanAra88** [comment]
Hi @martinarva, the monitor i use is the Tapo energy monitor. The "current consumption" is in W. 

As i say, your live cost is spot on - but its the daily, monthly, yearly that seems to be off for me :( 

See image:

<img width="334" alt="image" src="https://github.com/martinarva/dynamic_energy_cost/assets/43094647/e40c6769-cbfa-48ff-9911-c4d762955682">

**Comment by martinarva** [comment]
Maybe someone have any idea why this happens. Code that calculates the cost increment:

```python
    @callback
    def _handle_real_time_cost_update(self, event):
        """Update cumulative cost based on the real-time cost sensor updates."""
        new_state = event.data.get('new_state')
        if new_state is None or new_state.state in ('unknown', 'unavailable'):
            _LOGGER.debug("Skipping update due to unavailable state")
            return

        try:
            current_cost = Decimal(new_state.state)
            _LOGGER.debug(f"Current cost retrieved from state: {current_cost}")  # Log current cost

            if current_cost <= 0:  # Skip updates if the new cost is not positive
                _LOGGER.debug(f"Skipping update as the calculated cost {current_cost} is not positive.")
                return

            time_difference = now() - self._last_update
            hours_passed = Decimal(time_difference.total_seconds()) / Decimal(3600)  # Convert time difference to hours as Decimal
            _LOGGER.debug(f"Time difference calculated as: {time_difference}, which is {hours_passed} hours.")  # Log time difference in hours

            self._state += (current_cost * hours_passed).quantize(Decimal('0.01'))
            self._last_update = now()
            self.async_write_ha_state()
            _LOGGER.debug(f"Updated state to: {self._state} using cost: {current_cost} over {hours_passed} hours")
        except (InvalidOperation, TypeError) as e:
            _LOGGER.error(f"Error updating cumulative cost: {e}")
```


### Code Breakdown

1. **Method Decoration and Definition**:
   - `@callback`: This decorator is used to tell Home Assistant that this function should be run in the event loop, optimizing it for fast execution. It's important in the context of asynchronous programming, ensuring that this method does not block other operations.
   - `_handle_real_time_cost_update(self, event)`: This method is designed to handle updates triggered by a change in another sensor's state, with the `event` parameter carrying data related to this change.

2. **Handling of Event Data**:
   - `new_state = event.data.get('new_state')`: This line extracts the `new_state` from the event data. The `new_state` typically contains the latest state information about the sensor that triggered the event.

3. **State Validity Check**:
   - The method checks if `new_state` is `None` or its state is `'unknown'` or `'unavailable'`. If any of these conditions are true, the method logs a debug message and returns early without doing any further processing. This is crucial to ensure that the method only processes valid and available data.

4. **Cost Retrieval and Validation**:
   - `current_cost = Decimal(new_state.state)`: This line converts the state of the triggering sensor into a `Decimal`, which is a data type that provides precise fixed-point arithmetic. This step is necessary to handle financial calculations accurately.
   - The method then checks if `current_cost` is less than or equal to zero. If so, it logs this and returns early, as negative or zero costs do not contribute to cumulative calculations in this context.

5. **Time Difference Calculation**:
   - `time_difference = now() - self._last_update`: Here, `now()` represents the current time, and `self._last_update` is the time when the last update occurred. This line calculates how much time has passed since the last update.
   - `hours_passed = Decimal(time_difference.total_seconds()) / Decimal(3600)`: Converts the `time_difference` to the total number of seconds, and then divides by 3600 to convert this into hours. The result is stored as a `Decimal` for precision.

6. **State Update**:
   - `self._state += (current_cost * hours_passed).quantize(Decimal('0.01'))`: This line updates the sensor's state by adding the product of `current_cost` and `hours_passed`, quantized to two decimal places. This represents the accrued cost over the elapsed time, scaled to the cost rate per hour.
   - `self._last_update = now()`: Updates the last update timestamp to the current time.
   - `self.async_write_ha_state()`: Calls Home Assistant's method to write the updated state back to the system, ensuring that the state change is registered.

7. **Error Handling**:
   - The entire cost update logic is wrapped in a try-except block to catch and log any errors that might occur during execution, such as `InvalidOperation` or `TypeError`. This is important for debugging and ensuring the component doesn't crash from unhandled exceptions.

**Comment by DutchKillerbee** [comment]
@martinarva 
I would increase the accuracy
`self._state += (current_cost * hours_passed).quantize(Decimal('0.01'))`
to
`self._state += (current_cost * hours_passed).quantize(Decimal('0.0001'))`

If calculation is every 5 seconds, hours is a very small number. hours times a very little cost is 0.00
So add every 5 seconds 0.00 to the state makes sensor not accurate. 
Don't know if this will help in the factor 10 issue here but at least the state will become more accurate

**Comment by martinarva** [comment]
@DutchKillerbee , thanks for the insight. I increased accuracy and whis will be available in next release

**Comment by andiukas** [comment]
problem unsolved

**Comment by kiwibenis** [comment]
I am facing likely the same issue; calculated price is much to high.

Version: 0.5.0
Using Tibber, price is €/kwh
Measured with homematic HMIP-PSM in W
Energy usage sensor on this is in Wh, so not working for me

```
state_class: measurement
price_level: EXPENSIVE
max_price: 0.339
avg_price: 0.254
min_price: 0.181
off_peak_1: 0.267
peak: 0.223
off_peak_2: 0.321
unit_of_measurement: EUR/kWh
icon: mdi:currency-usd
friendly_name: Tibber Pulse Home Electricity price
```

```
state_class: measurement
interface_id: homematic.HmIP-RF
address: 003AA0C9A1A7B6:6
model: HmIP-PSM-2 QHJ
entity_type: generic
parameter: POWER
function: null
value_state: valid
unit_of_measurement: W
device_class: power
friendly_name: Garage Steckdose Power
```

The Dynamic Energy Costs sensors for the device are looking like:
![grafik](https://github.com/user-attachments/assets/2ea577f3-a304-4aeb-b45f-7eaa92608d9e)

With a usage of 3898,2 Wh (3,8kWh)
![grafik](https://github.com/user-attachments/assets/5256bd6d-788a-42dd-bbf3-903c03350113)

In total the costs should be around 0,80€
