### ISSUE TITLE
Set a sane default display precision 

### ISSUE THREAD

**Issue by vodkapmp** [martinarva/dynamic_energy_cost#32]
**Is your feature request related to a problem? Please describe.**
The integrations precision tends to go all over the place, and it'd be nice if it could have a default display precision set for the entities. Which users could change to be more precise if they wanted.

**Describe the solution you'd like**
Set default display precision to 1 or 2 decimal places.

**Describe alternatives you've considered**

**Additional context**
This just looks silly.
![image](https://github.com/martinarva/dynamic_energy_cost/assets/70449815/8e9027e7-b760-47af-9ae8-727874c02d95)

**Comment by wranglatang** [comment]
I would also like to see this :) 2 Decimal places is enough!

**Comment by dunxd** [comment]
2 decimal places makes sense for a currency.

**Comment by martinarva** [comment]
The problem is that increments can be very small, resulting in high precision with many decimal places. However, entities have SensorDeviceClass.MONETARY, and in the Home Assistant UI, it should display with two decimal places.

Here, you can see it shows two decimal places:
![Screenshot 2024-07-03 at 11 50 39](https://github.com/martinarva/dynamic_energy_cost/assets/77044330/c15d025d-90b3-4abf-968c-aa256dba569f)

And here, you can see the actual decimals:
![Screenshot 2024-07-03 at 11 50 45](https://github.com/martinarva/dynamic_energy_cost/assets/77044330/73b31f7a-c875-4ec7-9f13-3c6934aff2e1)

**Comment by vodkapmp** [comment]
I just don't see why setting the default **display** precision to something sane like 2 decimals isn't something you'd want to do? 
In a lot of cases when you work with this sensor (especially some apexcharts use) it wont default to 2 decimals automatically, even if it's a monetary one.

It isn't like doing this actually removes any precision, it's just a visual thing.
